#! /usr/bin/python
# -*- coding: utf-8 -*-
#-----------------------------------------------------------------------------
# Name:     quartus.py
# Purpose:
# Author:   Fabien Marteau <fabien.marteau@armadeus.com>
# Created:  21/07/2008
#-----------------------------------------------------------------------------
#  Copyright (2008)  Armadeus Systems
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#-----------------------------------------------------------------------------
# Revision list :
#
# Date       By        Changes
#
#-----------------------------------------------------------------------------

__doc__ = ""
__version__ = "1.0.0"
__versionTime__ = "21/07/2008"
__author__ = "Fabien Marteau <fabien.marteau@armadeus.com>"

import time
import datetime

from periphondemand.bin.define import *
from periphondemand.bin.utils.settings import Settings
from periphondemand.bin.utils.error    import Error
from periphondemand.bin.utils.display  import Display
from periphondemand.bin.utils          import wrappersystem as sy

from periphondemand.bin.core.component  import Component
from periphondemand.bin.core.port       import Port
from periphondemand.bin.core.interface  import Interface
from periphondemand.bin.core.hdl_file   import Hdl_file

settings = Settings()
display = Display()
TAB = "    "

def generatepinout(self,filename=None):
    """ Generate the constraint file in tcl for quartus fpga
    """
    if filename is None:
        filename =  settings.projectpath+\
                    SYNTHESISPATH+"/"+ \
                    settings.active_project.getName()+"_pinout"+ TCLEXT
    self.project = settings.active_project
    out = "# Pinout file, automaticaly generated by pod\n"
    out = out + "package require ::quartus::project\n"

    for interface in self.project.getPlatform().getInterfacesList():
        for port in interface.getPortsList():
            if port.forceDefined():
               out = out+TAB+'set_location_assignment '+str(port.getPosition())+\
                        ' -to force_'+str(port.getName())+";\n"
            else:
                for pin in port.getPinsList():
                    if pin.getConnections() != []:
                        connect = pin.getConnections()
                        out = out+TAB+'set_location_assignment '+\
                                port.getPosition()+" -to "+\
                                connect[0]["instance_dest"] + "_" +\
                                connect[0]["port_dest"]
                        if self.project.getInstance(
                            connect[0]["instance_dest"]).getInterface(
                                    connect[0]["interface_dest"]).getPort(
                                        connect[0]["port_dest"]).getSize() != "1":
                            out=out+"["+connect[0]["pin_dest"]+"]"
                        out = out +';\n'
    out = out + "#end\n"
    try:
        file = open(filename,"w")
    except IOError, e:
        raise Error(str(e),0)
    file.write(out)
    file.close()
    display.msg("Constraint file generated with name :"+filename)
    return filename

def generateTCL(self,filename=None):
    """ generate tcl script for quartus
    """
    print "TODO: Generate tcl script for quartus"

